### ISSUE TITLE
make some npm package out of your module

### ISSUE THREAD

**Issue by Mithgol** [lampaa/imageLib#1]
Originally suggested at http://habrahabr.ru/post/187452/#comment_6517570 when you announced the module.

**Comment by lampaa** [comment]
Hello!

Before creating the npm package, I will add gif format, crop function, and a couple of other necessary functions.

**Comment by lampaa** [comment]
I added package to npm repo: https://www.npmjs.org/package/imagelib

`npm install imagelib -g`

Install zlib:

`npm install zlib -g`
